name: CI/CD
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - .editorconfig
      - .gitignore

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    uses: ./.github/workflows/tests.yml
  draft_release:
    needs: [ tests ]
    uses: ./.github/workflows/create_release.yml