# This workflow is the entry point for all CI processes.
# It is from here that all other workflows are launched.
on:
  push:
    branches:
      - main
      - master
    paths-ignore:
      - '**.md'
      - .editorconfig
      - .gitignore
  pull_request:
    branches:
      - main
      - master
    paths-ignore:
      - '**.md'
      - .editorconfig
      - .gitignore

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    uses: ./.github/workflows/lint.yml
  typechecking:
    uses: ./.github/workflows/typechecking.yml
  tests:
    uses: ./.github/workflows/tests.yml
  draft_release:
    if: github.event_name == 'push' && github.ref_name == 'main'
    needs: [ typechecking, tests ]
    uses: ./.github/workflows/release.yml
  publish_release:
    needs: [ draft_release ]    
    runs-on: [ windows-latest ]
    steps:
      - name: Publish Release to Github
        uses: eregon/publish-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_id: ${{ steps.create_release.outputs.id }}

