name: CI/CD
on:
  push:
    branches:
      - main
      - master
    paths-ignore:
      - '**.md'
      - .editorconfig
      - .gitignore
  pull_request:
    branches:
      - main
      - master
    paths-ignore:
      - '**.md'
      - .editorconfig
      - .gitignore

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    uses: ./.github/workflows/tests.yml
  draft_release:
    if: github.event_name == 'push' && github.ref_name == 'main'
    needs: [ tests ]
    uses: ./.github/workflows/create_release.yml