name: Tests
on: [ workflow_call ]

concurrency:
  group: tests-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: 'bash'

jobs:
  unit:
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest ]
        # os: [ windows-latest, ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --frozen-lockfile
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
      - name: Run Lint
        run: yarn run lint
      - name: Run Typecheck
        run: yarn run typecheck
      - name: Run Main Tests
        run: yarn run test:main
      - name: Run Preload Tests
        run: yarn run test:preload
      - name: Run Renderer Tests
        run: yarn run test:renderer
      - name: Run End to End Tests (Linux)
        run: xvfb-run --auto-servernum --server-args="-screen 0 1280x960x24" -- yarn run test:e2e
        if: matrix.os == 'ubuntu-latest'  
      - name: Run End to End Tests (Others)
        run: yarn run test:e2e
        if: matrix.os != 'ubuntu-latest'